### ISSUE TITLE
NFProfile in TS29510_Nnrf_NFDiscovery != TS29510_Nnrf_NFManagement

### ISSUE THREAD

**Issue by gatopeich** [jdegre/5GC_APIs#11]
We cannot validate an NFProfile as produced by the NFManagement API with the NFDiscovery's version of it.

e.g.: "heartBeatTimer" property does not exist in NFDiscovery::NFProfile

Why do we keep 2 definitions of the same class?

**Comment by jdegre** [comment]
@gatopeich,
NFManagement and NFDiscovery are 2 distinct APIs. The fact that both of them define an object with a same type name (NFProfile) is simply annecdotical and, of course, it is not expected to use the type in one of the APIs to validate a instance object received in the other API. We could have used different names for both object types and this possibility was indeed discussed long ago; eventually, we opted for using the same name, though.

As you have seen, the NF Profile definition in the NFManagement API contains many attributes that only make sense in that API; one example is "heartBeatTimer". This attribute makes no sense in the NF Discovery API. Same for all the "allowedXXX" attributes; those are only meaningful in the NF Management API.

**Comment by gatopeich** [comment]
Thanks for the background.
It is a bit unfortunate because it breaks my assumption that names would not collide within the same TS, to use the TS number as a namespace of sorts: "fully qualified schema name" = <ts>.<schema> ... Not anymore! :-)
