### ISSUE TITLE
Changes in the UDR API

### ISSUE THREAD

**Issue by UchihaItachi93** [jdegre/5GC_APIs#12]
Hi, 
I don't think this qualifies as an issue, but I was not sure how to contact you regarding the change in certain APIs. For example, the UDR Authentication Data API  (in UDR subscription Data APIs ) response data has changed in the last week or so.  Looking at the 3GPP releases, there has been no new official release regarding the same(TS29.505 and TS29.504).  Is it based on any existing CR which will come along with the next release ? Am I missing anything about the releases?  

P.S Sorry for raising an extraneous issue, but I had no other way of messaging you

**Comment by jdegre** [comment]
@UchihaItachi93, there will be new official versions of the TS's published on the 3GPP web site in 2 weeks or so. In the mean time, the changes you saw in the repo are those agreed by the Working Groups, which are "temptative" until they are formally approved by the plenary meeting, next week.
That's the reason for the "work in progress" tag I added in readme.md file.

**Comment by UchihaItachi93** [comment]
@jdegre    I should have seen the line in README.md before raising the issue.My bad
 Thank you for taking the time to answer.  I really appreciate it.
