### ISSUE TITLE
TS29572_Nlmf_Location.yaml: There is not FLR of CivicAddress

### ISSUE THREAD

**Issue by mnm-analytics** [jdegre/5GC_APIs#18]
Hi, @jdegre.

I confirmed exists FLR in 3GPP TS 29.572 V15.3.0 (2019-03); Table 6.1.6.2.14-1: Definition of type CivicAddress.
But, I didn't confirm it in TS29572_Nlmf_Location.yaml.

**Comment by jdegre** [comment]
hi @mnm-analytics,
you're absolutely right; good catch! i'll make sure this is corrected in the next release of the 3GPP specs.
thanks for reporting!
