### ISSUE TITLE
5GC_APIs/master/TS29505_Subscription_Data.yaml - wrong spelling

### ISSUE THREAD

**Issue by kpopovic** [jdegre/5GC_APIs#29]
Hello,

please correct small spelling error in [TS29505_Subscription_Data.yaml](https://jdegre.github.io/editor/?url=https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29505_Subscription_Data.yaml).
Subs To Nofify (Collection) --> Subs To **Notify** (Collection)

location of spelling error:

    get:
      summary: Retrieves the list of subscriptions
      operationId: **QuerySubsToNotify**
      tags:
        - Subs To Nofify (Collection)  <----------------- **to be fixed**

/subscription-data/subs-to-notify:
    post:
      summary: Subscription data subscriptions
      operationId: **SubscriptionDataSubscriptions**
      tags:
        - Subs To Nofify (Collection) <----------------- **to be fixed**

**Comment by jdegre** [comment]
Hi @kpopovic, thanks for reporting this.
I'll take care this is fixed for the next round of upates of the APIs (there is one scheduled for later this month, but we are late for this one, so I'll schedule it for the next update in Q3).
I'll leave the issue open as a reminder.

**Comment by jdegre** [comment]
Closing this issue, since a correction has been already proposed to the forthcoming 3GPP meeting, to be held in 2 weeks
