### ISSUE TITLE
5GC_APIs/master/TS29505_Subscription_Data.yaml - Event Exposure Group Subscriptions (Document) title is missing

### ISSUE THREAD

**Issue by kpopovic** [jdegre/5GC_APIs#30]
Hello,
**Event Exposure Group Subscriptions (Collection)** - title tag exists

**Event Exposure Group Subscriptions (Document)** - title tag doesn't exists
PUT ​/subscription-data​/**group-data​**/{ueGroupId}​/ee-subscriptions​/{subsId}
DELETE ​/subscription-data​/**group-data**​/{ueGroupId}​/ee-subscriptions​/{subsId}
PATCH ​/subscription-data​/**group-data​**/{ueGroupId}​/ee-subscriptions​/{subsId}
GET ​/subscription-data​/**group-data**​/{ueGroupId}​/ee-subscriptions​/{subsId}

currently those 4 http methods are defined in Event Exposure Subscription (Document) which depends to ueId.
![eeGroupSubsDoc](https://user-images.githubusercontent.com/1502762/85849842-fec78280-b7ab-11ea-97d1-fa3b4cce72a2.png)

**Comment by jdegre** [comment]
thanks for reporting, @kpopovic; i'll make sure this is fixed in the next Working Group meeting, in August.
I'll leave the issue open until then.

**Comment by jdegre** [comment]
Closing the issue, since this was fixed in last 3GPP meeting.
