### ISSUE TITLE
https://github.com/jdegre/5GC_APIs/blob/master/TS29505_Subscription_Data.yaml - GET /subscription-data/{ueId}/context-data

### ISSUE THREAD

**Issue by kpopovic** [jdegre/5GC_APIs#32]
Hello,

please check if minItems=1 should be corrected to minItems=2 ? 29.505 / 16.2.0 / 16.3.0 says it needs to.
https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=3406

https://github.com/jdegre/5GC_APIs/blob/master/TS29505_Subscription_Data.yaml#L4079

`ContextDatasetNames:`
`      type: array`
`    items:`
      `  $ref: '#/components/schemas/ContextDataSetName'`
    `  minItems: 1` --> **should be minItems=2** ?
`      uniqueItems: true`

3GPP TS 29.505 V16.3.0 (2020-06)
Table 5.2.32.3.1-1: URI query parameters supported by the GET method on this resource

context-dataset-names | array(ContextDataSetName) | M | 2..N | If   included, this IE shall contain the names of context data sets to be   retrieved. If not included, all context data sets shall be returned.
-- | -- | -- | -- | --

_note: This part of sentence in doc 29.505 has no sense: "If not included, all context data sets shall be returned."_ It is mandatory, so it needs to be always included.

**Comment by jdegre** [comment]
thanks for reporting it, @kpopovic; i will propose a correction to the next 3GPP meeting, to fix this problem.

**Comment by jdegre** [comment]
Closing this issue, since the correction has been already submitted to the forthcoming 3GPP meeting, to be held in 2 weeks (pending a final decision, but it _will_ be addressed and concluded in one way or another)
