### ISSUE TITLE
(a question. not an issue) - how to use Namf-comm on free5gc's AMF

### ISSUE THREAD

**Issue by zalfia** [jdegre/5GC_APIs#43]
Hi,

I'm working on a demo where i need an external system to API with free5gc's AMF and 'command' it to release a UE.

Your 5GC_APIs repository points to https://jdegre.github.io/loader.html?yaml=TS29518_Namf_Communication.yaml 

my question is - what are the oAuth2ClientCredentials I'm supposed to use (client_id, client_secret) for free5gc's AMF ?

I'd appreciate your help on this.

**Comment by jdegre** [comment]
hi @zalfia; i'm not very familiar with the details of free5gc.

in any case, the 3GPP standard require that a consumer of any Network Function that has deployed Oauth2-based authorization, gets an Oauth2 access token **from NRF** (Access Token Request API).

then, you need to send such access token as bearer token to invoke any of the AMF API operations (for example, POST request to the "/ue-contexts/{ueContextId}/release" resource of the Namf_Communication API).

**Comment by zalfia** [comment]
Thanks for the prompt reply !

**Comment by cheungderek** [comment]
Is there any tutorial or examples in how to use this 5G API to say setup a PDU session?
