### ISSUE TITLE
Extra space in TS29505_Subscription_Data.yaml

### ISSUE THREAD

**Issue by UchihaItachi93** [jdegre/5GC_APIs#5]
Hi,
 There seems to be a couple of extra spaces in the file  TS29505_Subscription_Data.yaml in lines 1282 and lines 1310.
i.e  'https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29571_CommonData.yaml #/components/schemas/VarUeId
has an extra space between the 'yaml' and the '#'
. It causes problems when you are trying to dereference the yaml file using some automated tool. 
If you have the time, please have  a look at the aforementioned 

Thanks

**Comment by jdegre** [comment]
Thanks @UchihaItachi93; not sure how those whitespaces have ended up there... the ref's seem to be correct in the original 3GPP specs. Anyhow, I have fixed them. Cheers!
