### ISSUE TITLE
Mismatched case in reference to oAuth2ClientCredentials security scheme

### ISSUE THREAD

**Issue by tedepstein** [jdegre/5GC_APIs#7]
FYI, a number of the OpenAPI Documents contain a top-level Security Requirements Object like this one:

```
security:
  - {}
  - oAuth2Clientcredentials:
    - nnssf-nssaiavailability
```

The defined name of the referenced security scheme is `oAuth2ClientCredentials` with an upper-case 'C' in 'Credentials.' [KaiZen OpenAPI Editor](https://github.com/RepreZen/KaiZen-OpenAPI-Editor) flagged this as an error.

`TS29531_Nnssf_NSSAIAvailability.yaml` is one of several documents that has this error.

**Comment by jdegre** [comment]
Thanks a lot for reporting, @tedepstein; I know this problem existed for several APIs in the past, and I thought all of them had been fixed, but apparently not!  I'll go again over all of the API files, and provide a fix asap.

**Comment by jdegre** [comment]
Closing this; all the affected APIs were fixed in the last 3GPP WG meeting, and should be published in a week or two.
